#DB
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/team_c
    username: team_c
    password: green502
    jdbc-url: jdbc:mariadb://192.168.0.144:3306/team_c
  #mybatis


mybatis:
  type-aliases-package: com.green.boardver3
  mapper-locations: mapper/**/*.xml

#SWAGGER
springdoc:

  swagger-ui:
    path: /swagger.html
    operations-sorter : method


file:
  dir: D:\download\
